name: penyewaan_alat_camping
description: >
  Model domain penyewaan alat camping dalam Dart murni (tanpa Flutter),
  dibuat untuk tugas P02 — Dart OOP Challenge.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^4.0.0
